import smtplib
from email.message import EmailMessage
import streamlit as st


def send_split_email(
    recipient_email,
    merchant,
    person_subtotals,
    person_totals,
    tax,
    discount,
    receipt_total,
    receipt_bytes=None,
    receipt_filename=None
):
    sender_email = st.secrets["GMAIL_ADDRESS"]
    app_password = st.secrets["GMAIL_APP_PASSWORD"]

    subject = f"SplitSnap - Bill Split for {merchant}"

    # ========================================================
    # PLAIN TEXT EMAIL
    # ========================================================

    text_body = f"""
SplitSnap - AI Receipt & Bill Splitter

Merchant: {merchant}

Receipt Total: ₹{receipt_total:.2f}

Bill Split
-------------------------
"""

    for person in person_totals:

        subtotal = person_subtotals.get(
            person,
            0
        )

        final_amount = person_totals[person]

        text_body += (
            f"{person}\n"
            f"  Items: ₹{subtotal:.2f}\n"
            f"  Final: ₹{final_amount:.2f}\n\n"
        )

    text_body += f"""
Tax: ₹{tax:.2f}
Discount: ₹{discount:.2f}

-------------------------
Total: ₹{receipt_total:.2f}

Split Verified: YES

This email was generated by SplitSnap.
"""

    # ========================================================
    # HTML EMAIL
    # ========================================================

    rows = ""

    for person in person_totals:

        subtotal = person_subtotals.get(
            person,
            0
        )

        final_amount = person_totals[person]

        rows += f"""
        <tr>
            <td style="padding: 12px 8px;
                       border-bottom: 1px solid #eeeeee;">
                <strong>{person}</strong>
            </td>

            <td style="padding: 12px 8px;
                       text-align: right;
                       border-bottom: 1px solid #eeeeee;">
                ₹{subtotal:.2f}
            </td>

            <td style="padding: 12px 8px;
                       text-align: right;
                       border-bottom: 1px solid #eeeeee;">
                <strong>₹{final_amount:.2f}</strong>
            </td>
        </tr>
        """

    html_body = f"""
<!DOCTYPE html>

<html>

<head>

<meta charset="UTF-8">

<meta name="viewport"
      content="width=device-width,
               initial-scale=1.0">

<title>SplitSnap Bill Split</title>

</head>

<body style="
    margin: 0;
    padding: 0;
    background-color: #f5f3fa;
    font-family: Arial, Helvetica, sans-serif;
">

<div style="
    max-width: 650px;
    margin: 30px auto;
    background: white;
    border-radius: 12px;
    overflow: hidden;
">

    <!-- HEADER -->

    <div style="
        padding: 24px;
        background-color: #6c4ab6;
        color: white;
    ">

        <h1 style="
            margin: 0;
            font-size: 26px;
        ">
            🧾 SplitSnap
        </h1>

        <p style="
            margin: 6px 0 0 0;
            font-size: 14px;
        ">
            AI Receipt & Bill Splitter
        </p>

    </div>


    <!-- CONTENT -->

    <div style="
        padding: 25px;
    ">

        <h2 style="
            margin-top: 0;
        ">
            {merchant}
        </h2>


        <!-- TOTAL -->

        <div style="
            padding: 18px;
            margin: 20px 0;
            background-color: #f5f3fa;
            border-radius: 10px;
        ">

            <p style="
                margin: 0;
                font-size: 14px;
            ">
                Receipt Total
            </p>

            <p style="
                margin: 5px 0 0 0;
                font-size: 28px;
                font-weight: bold;
            ">
                ₹{receipt_total:.2f}
            </p>

        </div>


        <!-- SPLIT TABLE -->

        <h3>
            Bill Split
        </h3>

        <table style="
            width: 100%;
            border-collapse: collapse;
        ">

            <thead>

                <tr>

                    <th style="
                        padding: 10px 8px;
                        text-align: left;
                        border-bottom: 2px solid #dddddd;
                    ">
                        Person
                    </th>

                    <th style="
                        padding: 10px 8px;
                        text-align: right;
                        border-bottom: 2px solid #dddddd;
                    ">
                        Items
                    </th>

                    <th style="
                        padding: 10px 8px;
                        text-align: right;
                        border-bottom: 2px solid #dddddd;
                    ">
                        Final
                    </th>

                </tr>

            </thead>

            <tbody>

                {rows}

            </tbody>

        </table>


        <!-- TAX / DISCOUNT -->

        <div style="
            margin-top: 25px;
            padding-top: 15px;
            border-top: 1px solid #eeeeee;
        ">

            <p>
                Tax:
                <strong>₹{tax:.2f}</strong>
            </p>

            <p>
                Discount:
                <strong>₹{discount:.2f}</strong>
            </p>

        </div>


        <!-- FINAL TOTAL -->

        <div style="
            margin-top: 20px;
            padding: 18px;
            border-top: 2px solid #333333;
        ">

            <table style="
                width: 100%;
            ">

                <tr>

                    <td>
                        <strong>Total</strong>
                    </td>

                    <td style="
                        text-align: right;
                        font-size: 22px;
                        font-weight: bold;
                    ">
                        ₹{receipt_total:.2f}
                    </td>

                </tr>

            </table>

        </div>


        <!-- VERIFIED -->

        <div style="
            margin-top: 20px;
            padding: 14px;
            background-color: #eaf7ee;
            border-radius: 8px;
            text-align: center;
        ">

            <strong>
                ✅ Split Verified
            </strong>

        </div>

    </div>


    <!-- FOOTER -->

    <div style="
        padding: 18px;
        background-color: #fafafa;
        text-align: center;
        color: #777777;
        font-size: 12px;
    ">

        This email was generated by SplitSnap.

    </div>

</div>

</body>

</html>
"""

    # ========================================================
    # CREATE EMAIL
    # ========================================================

    message = EmailMessage()

    message["Subject"] = subject
    message["From"] = sender_email
    message["To"] = recipient_email

    # Plain-text fallback
    message.set_content(
        text_body
    )

    # HTML version
    message.add_alternative(
        html_body,
        subtype="html"
    )

    # ========================================================
    # ATTACH RECEIPT
    # ========================================================

    if (
        receipt_bytes
        and receipt_filename
    ):

        if receipt_filename.lower().endswith(
            ".png"
        ):

            maintype = "image"
            subtype = "png"

        elif receipt_filename.lower().endswith(
            ".webp"
        ):

            maintype = "image"
            subtype = "webp"

        else:

            maintype = "image"
            subtype = "jpeg"

        message.add_attachment(
            receipt_bytes,
            maintype=maintype,
            subtype=subtype,
            filename=receipt_filename
        )

    # ========================================================
    # SEND EMAIL
    # ========================================================

    with smtplib.SMTP(
        "smtp.gmail.com",
        587
    ) as server:

        server.starttls()

        server.login(
            sender_email,
            app_password
        )

        server.send_message(
            message
        )

    return True